### ISSUE TITLE
packager workarounds for approval_utilities

### ISSUE THREAD

**Issue by schmonz** [approvals/ApprovalTests.Python#131]
Hi! I maintain packages for [py-approvaltests](https://pkgsrc.se/devel/py-approvaltests) and now also [py-approval-utilities](https://pkgsrc.se/devel/py-approval-utilities) in [pkgsrc](https://pkgsrc.org), a cross-platform Unix package manager.

I've had to work around a couple build problems with `approval_utilities` (ever since it became a separate distribution from `approvaltests`), both to do with version numbering:

1. Not finding a `version.py` because it's looking in the wrong place:

```
Traceback (most recent call last):
  File "/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/setup.approval_utilities.py", line 8, in <module>
    version=get_version(),
  File "/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/setup_utils.py", line 15, in get_version
    ).read_text()
  File "/opt/pkg/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/pkg/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/approvaltests/version.py'
```

I worked around this like so:

```diff
--- setup_utils.py.orig	2022-10-16 20:31:10.000000000 +0000
+++ setup_utils.py
@@ -11,7 +11,7 @@ def get_parent_directory():

 def get_version():
     _version_file_contents = (
-        get_parent_directory() / "approvaltests" / "version.py"
+        get_parent_directory() / "approval_utilities" / "version.py"
     ).read_text()
     matched = re.search(r'"(.*)"', _version_file_contents)
     return matched.group(1) if matched is not None else "UNKNOWN VERSION"
```

2. Not finding a `version.py` because in the right place, there isn't one:
```
Traceback (most recent call last):
  File "/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/setup.approval_utilities.py", line 8, in <module>
    version=get_version(),
  File "/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/setup_utils.py", line 15, in get_version
    ).read_text()
  File "/opt/pkg/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/pkg/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/tmp/pkgsrc/obj/devel/py-approval-utilities/work.magnetic-babysitter/approval_utilities-8.0.0/approval_utilities/version.py'
```

I worked around this by creating one, passing down the version of `approval_utilities` known to the pkgsrc package's `Makefile` :

```make
post-extract:
	${ECHO} "version_number = \"v${PKGVERSION_NOREV}\"" > ${WRKSRC}/approval_utilities/version.py
```

With these two changes applied, the build (via `python3.10 setup.approval_utilities.py build`) completes and I've not encountered any further problems. I'd be happy for future releases of `approval_utilities` to ship with their own correct `version.py`.

(I'd also be very happy to join the mob sometime, but the timeslot is tough for me and it hasn't worked out yet. Hence my finally getting around to filing this.)

**Comment by nitsanavni** [comment]
@schmonz @isidore maybe we could think of an option to mob outside of regular mobbing hours :)
