### ISSUE TITLE
verify_file() gives traceback when files match

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.Python#31]
**Problem**

Using `verify_file()` will give a traceback, reporting that the file is in use, if the files match.

**Reproduction:**

Steps to reproduce:

1. Run the code below, approving the output
2. Re-run this code

Expected behaviour: Test passes
Actual behaviour:

Traceback:

```Ran 1 test in 0.047s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "C:\Anaconda\lib\unittest\case.py", line 329, in run
    testMethod()
  File "[directoryname]\test_bug.py", line 28, in test_simple
    verify_file(output_file, self.reporter)
  File "C:\Anaconda\lib\site-packages\approvaltests\approvals.py", line 55, in verify_file
    verify(file_contents, reporter)
  File "C:\Anaconda\lib\site-packages\approvaltests\approvals.py", line 35, in verify
    verify_with_namer(data, get_default_namer(), reporter)
  File "C:\Anaconda\lib\site-packages\approvaltests\approvals.py", line 42, in verify_with_namer
    error = approver.verify(namer, writer, reporter)
  File "C:\Anaconda\lib\site-packages\approvaltests\file_approver.py", line 17, in verify
    ok = self.verify_files(approved, received, reporter)
  File "C:\Anaconda\lib\site-packages\approvaltests\file_approver.py", line 24, in verify_files
    os.remove(received_file)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process:
 '[test-code-location]\GettingStartedTest.test_simple.received.txt'


Process finished with exit code 1
```

The test code is:

```python
# Based on "GETTING STARTED" at https://github.com/approvals/ApprovalTests.Python
# Modified to write our own output file, and use verify_file()
import unittest

from approvaltests.approvals import verify_file, get_default_namer
from approvaltests.reporters.generic_diff_reporter_factory import GenericDiffReporterFactory


class GettingStartedTest(unittest.TestCase):
    def setUp(self):
        self.reporter = GenericDiffReporterFactory().get_first_working()

    def test_simple(self):
        # We are going to be writing our own output file - write it to
        # the standard location:
        namer = get_default_namer()
        output_file = namer.get_received_filename()

        # Simulate testing some complex functionality that writes out its own data
        # to a supplied file name:
        with open(output_file, 'wb') as output:
            output.write('Hello')

        # Once we have "Approved" the output, ApprovalTests will throw:
        # WindowsError: [Error 32] The process cannot access the file because it is
        # # being used by another process:
        # '[directoryname]\\GettingStartedTest.test_simple.received.txt'
        verify_file(output_file, self.reporter)


if __name__ == "__main__":
    unittest.main()
```

**Comment by claremacrae** [comment]
The problem is this code in approvals.py:

```python
def verify_file(file_name, reporter=None):
    with open(file_name, 'r') as f:
        file_contents = f.read()
        verify(file_contents, reporter)
```

The call to verify() ultimately ends up calling this, which attempts to delete the received file, if the files are the same:

```python
    def verify_files(self, approved_file, received_file, reporter):
        if self.are_files_the_same(approved_file, received_file):
            os.remove(received_file)
            return True

        reporter.report(received_file, approved_file)
        return False
```

The problem is that the call to `verify()` is within the scope of the `with` block, so the file object is still open, and the file cannot be removed.

The fix is this - out-denting the `verify()` call, so the file object is closed before deletion is attempted:

```python
def verify_file(file_name, reporter=None):
    with open(file_name, 'r') as f:
        file_contents = f.read()
    verify(file_contents, reporter)
```

**Comment by tdpreece** [comment]
Thanks for the message!
I think this is a problem with Windows only, we'll have to look into running the tests on Windows in Travis.
Your out-denting fix looks good.  Would you like to submit a pull request with it?

Tim

**Comment by tdpreece** [comment]
Thanks for reporting this.

I have just committed the out-denting fix: https://github.com/approvals/ApprovalTests.Python/commit/514ceb5f79558a9b716e8be685238d0353da451d

I have raised a new issue for adding CI tests for Windows: https://github.com/approvals/ApprovalTests.Python/issues/39
