### ISSUE TITLE
version 0.2.7 appears to break tests that use Namer

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.Python#68]
Is there any chance someone could document the breaking changes in this release please, and how to update code?

I've had to change my requirements to pin to the previous version:

```
approvaltests==0.2.6
```

This was the line in my tests that gave an error:

```python
from approvaltests.approvals import verify_with_namer, Namer
```

I'll come back shortly and record the error message once I've committed the changes...

**Comment by claremacrae** [comment]
The output when running with approvaltests 0.2.7 is:

```
Launching unittests with arguments python -m unittest discover -s /Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests -t /Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests in /Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests


Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_markdown_conversion
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests/test_markdown_conversion.py", line 4, in <module>
    from approvaltests.approvals import verify_with_namer, Namer
ImportError: cannot import name 'Namer' from 'approvaltests.approvals' (/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/approvals.py)
```

**Comment by tdpreece** [comment]
@claremacrae I think the problem above is probably the result of the following change (see [commit 1c2f3a8c6eeae355f663ecf358e350df38d77727](https://github.com/approvals/ApprovalTests.Python/commit/1c2f3a8c6eeae355f663ecf358e350df38d77727))

```
diff --git a/approvaltests/approvals.py b/approvaltests/approvals.py
index f27e21d..697573b 100644
--- a/approvaltests/approvals.py
+++ b/approvaltests/approvals.py
@@ -1,9 +1,10 @@
+import io
 from threading import local
 import xml.dom.minidom

 from approvaltests import to_json
 from approvaltests.approval_exception import ApprovalException
-from approvaltests.core.namer import Namer, StackFrameNamer
+from approvaltests.core.namer import StackFrameNamer
 from approvaltests.core.scenario_namer import ScenarioNamer
 from approvaltests.file_approver import FileApprover
 from approvaltests.list_utils import format_list
```

`Namer` is defined in `approvaltests.core.namer` so amending your tests to import from there should fix this for now: `from approvaltests.core.namer import Namer`.

Going forward, I wonder if we should import `Namer` in `approvaltests/__init__.py` so that we have a more clearly defined public interface to the approvaltests package. This would allow you to do `from approvaltests import Namer`.

Changing the `from ... import *` in `approvaltests/__init__.py` to explicitly import the classes/functions that should be exposed via the public api would also help to avoid problems like the one experienced in this issue from happening.

**Comment by claremacrae** [comment]
@tdpreece Thanks very much for the reply...

When I update to `approvaltests==0.2.7`, and add this line:

```python
from approvaltests.core.namer import Namer
```

I then get:

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests/test_markdown_conversion.py", line 51, in test_convert_markdown_for_pandoc
    verify_with_namer(converted_markdown, namer, reporter)
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/approvals.py", line 112, in verify_with_namer
    error = approver.verify(namer, writer, reporter)
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/file_approver.py", line 12, in verify
    base = namer.get_basename()
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/core/namer.py", line 25, in get_basename
    file_name = self.get_file_name()
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/core/namer.py", line 16, in get_file_name
    raise Exception("This class is abstract, override this method in a subclass")
Exception: This class is abstract, override this method in a subclass
```

I tried this instead:

```python
from approvaltests.pytest import PyTestNamer
```

And got:

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_markdown_conversion
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/sphinx/tests/test_markdown_conversion.py", line 5, in <module>
    from approvaltests.pytest import PyTestNamer
ImportError: cannot import name 'PyTestNamer' from 'approvaltests.pytest' (/Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/build/venv/lib/python3.7/site-packages/approvaltests/pytest/__init__.py)
```

**Comment by tdpreece** [comment]
`Namer` was made abstract in https://github.com/approvals/ApprovalTests.Python/commit/02db0956ac7eaa02374e41b5381fdc30d3dc103a. 

`PyTestNamer` lives in `approvaltests.pytest.namer` thus you should be able to import it like:

```
from approvaltests.pytest.namer import PyTestNamer
```

**Comment by claremacrae** [comment]
> `Namer` was made abstract in [02db095](https://github.com/approvals/ApprovalTests.Python/commit/02db0956ac7eaa02374e41b5381fdc30d3dc103a).
> 
> `PyTestNamer` lives in `approvaltests.pytest.namer` thus you should be able to import it like:
> 
> ```
> from approvaltests.pytest.namer import PyTestNamer
> ```

That didn't work, but using `StackFrameNamer` worked and with:

```
from approvaltests import StackFrameNamer
...
            namer = StackFrameNamer('.md')
            verify_with_namer(converted_markdown, namer, reporter)
```

**Comment by claremacrae** [comment]
I'm closing this now - so much time has passed, and other changes made, that it's not worth spending any development team time on...
